// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxPThQDckYjEmctgAYq1Xdt18eGFP2d4s',
    appId: '1:424764710953:web:470d0411e3c603c47e7c38',
    messagingSenderId: '424764710953',
    projectId: 'indecisionmate-24594',
    authDomain: 'indecisionmate-24594.firebaseapp.com',
    storageBucket: 'indecisionmate-24594.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxh6shyLfDUu98quRWAcqSyehnS71sxCs',
    appId: '1:424764710953:android:8ec7d42ae0e333957e7c38',
    messagingSenderId: '424764710953',
    projectId: 'indecisionmate-24594',
    storageBucket: 'indecisionmate-24594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIZjM6krXtbcIigQSMEpfReKSSFoBhuFs',
    appId: '1:424764710953:ios:74e6dc3d69c839517e7c38',
    messagingSenderId: '424764710953',
    projectId: 'indecisionmate-24594',
    storageBucket: 'indecisionmate-24594.appspot.com',
    iosBundleId: 'com.example.indecisionmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIZjM6krXtbcIigQSMEpfReKSSFoBhuFs',
    appId: '1:424764710953:ios:e58d141fe7c41ace7e7c38',
    messagingSenderId: '424764710953',
    projectId: 'indecisionmate-24594',
    storageBucket: 'indecisionmate-24594.appspot.com',
    iosBundleId: 'com.example.indecisionmate.RunnerTests',
  );
}
